version: "3"

networks:
  default:
    name: vibedeploy-shared
    external: true

services:
  web:
    build:
      context: ./web-react
      dockerfile: ./Dockerfile
    container_name: easy-deploy-web
    restart: always
    ports:
      - '5999:80'
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: easy-deploy-server
    restart: always
    ports:
      - '9999:8008'
    extra_hosts:
      - "host.docker.internal:host-gateway"
